# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27dfaea57b111c6c63a218cea50097b14f3ceda8920def480a65f13baa06144c3b8bde74bbec06eddf33670878ff7c633423c7de37667d587c1c03dadce414ea

test:
  secret_key_base: 2324b0a4925fd70ea9180359f8cbda2b06e4b889f31896fb55a1fa0736e4deb48fbaa05544182f2e7dbd820ecfa7c72bb9d288f6b67e877f8008d43d89d1e1d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
